-- CREATE SCHEMA public;
-- CREATE DATABASE postgres;
-- CREATE SCHEMA IF NOT EXISTS anime
-- CREATE TABLE anime (id SERIAL PRIMARY KEY, name VARCHAR(255));

-- CREATE SCHEMA IF NOT EXISTS anime;
-- CREATE TABLE anime (id SERIAL PRIMARY KEY, name VARCHAR(255));

CREATE SCHEMA IF NOT EXISTS anime;
CREATE TABLE anime (id SERIAL PRIMARY KEY, name VARCHAR(255));

